//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by Unity Input System package.
//     Manual edits may be lost when regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace SwarmAI.Demo
{
    public partial class @SwarmDemoInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        
        public @SwarmDemoInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""SwarmDemoInputActions"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef0123456789"",
            ""actions"": [
                {
                    ""name"": ""Pan"",
                    ""type"": ""Value"",
                    ""id"": ""b2c3d4e5-f6a7-8901-bcde-f01234567890"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""c3d4e5f6-a7b8-9012-cdef-012345678901"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateButton"",
                    ""type"": ""Button"",
                    ""id"": ""d4e5f6a7-b8c9-0123-def0-123456789012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateDelta"",
                    ""type"": ""Value"",
                    ""id"": ""e5f6a7b8-c9d0-1234-ef01-234567890123"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Arrows"",
                    ""id"": ""f6a7b8c9-d0e1-2345-f012-345678901234"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a7b8c9d0-e1f2-3456-0123-456789012345"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b8c9d0e1-f2a3-4567-1234-567890123456"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c9d0e1f2-a3b4-5678-2345-678901234567"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d0e1f2a3-b4c5-6789-3456-789012345678"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e1f2a3b4-c5d6-7890-4567-890123456789"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a3b4c5-d6e7-8901-5678-901234567890"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3b4c5d6-e7f8-9012-6789-012345678901"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Demo"",
            ""id"": ""b4c5d6e7-f8a9-0123-7890-123456789012"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""c5d6e7f8-a9b0-1234-8901-234567890123"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""d6e7f8a9-b0c1-2345-9012-345678901234"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""e7f8a9b0-c1d2-3456-0123-456789012345"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""f8a9b0c1-d2e3-4567-1234-567890123456"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number1"",
                    ""type"": ""Button"",
                    ""id"": ""a9b0c1d2-e3f4-5678-2345-678901234567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number2"",
                    ""type"": ""Button"",
                    ""id"": ""b0c1d2e3-f4a5-6789-3456-789012345678"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number3"",
                    ""type"": ""Button"",
                    ""id"": ""c1d2e3f4-a5b6-7890-4567-890123456789"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number4"",
                    ""type"": ""Button"",
                    ""id"": ""d2e3f4a5-b6c7-8901-5678-901234567890"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number5"",
                    ""type"": ""Button"",
                    ""id"": ""e3f4a5b6-c7d8-9012-6789-012345678901"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number6"",
                    ""type"": ""Button"",
                    ""id"": ""f4a5b6c7-d8e9-0123-7890-123456789012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""a5b6c7d8-e9f0-1234-8901-234567890123"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionG"",
                    ""type"": ""Button"",
                    ""id"": ""b6c7d8e9-f0a1-2345-9012-345678901234"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionH"",
                    ""type"": ""Button"",
                    ""id"": ""c7d8e9f0-a1b2-3456-0123-456789012345"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionN"",
                    ""type"": ""Button"",
                    ""id"": ""d8e9f0a1-b2c3-4567-1234-567890123456"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionF"",
                    ""type"": ""Button"",
                    ""id"": ""e9f0a1b2-c3d4-5678-2345-678901234567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionX"",
                    ""type"": ""Button"",
                    ""id"": ""f0a1b2c3-d4e5-6789-3456-789012345678"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Plus"",
                    ""type"": ""Button"",
                    ""id"": ""a1b2c3d4-e5f6-7890-4567-890123456789"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Minus"",
                    ""type"": ""Button"",
                    ""id"": ""b2c3d4e5-f6a7-8901-5678-901234567890"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""c3d4e5f6-a7b8-9012-6789-012345678901"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d4e5f6a7-b8c9-0123-7890-123456789012"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5f6a7b8-c9d0-1234-8901-234567890123"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6a7b8c9-d0e1-2345-9012-345678901234"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7b8c9d0-e1f2-3456-0123-456789012345"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8c9d0e1-f2a3-4567-1234-567890123456"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Number1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9d0e1f2-a3b4-5678-2345-678901234567"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Number2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0e1f2a3-b4c5-6789-3456-789012345678"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Number3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1f2a3b4-c5d6-7890-4567-890123456789"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Number4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a3b4c5-d6e7-8901-5678-901234567890"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Number5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3b4c5d6-e7f8-9012-6789-012345678901"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Number6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4c5d6e7-f8a9-0123-7890-123456789012"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5d6e7f8-a9b0-1234-8901-234567890123"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ActionG"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6e7f8a9-b0c1-2345-9012-345678901234"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ActionH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7f8a9b0-c1d2-3456-0123-456789012345"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ActionN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8a9b0c1-d2e3-4567-1234-567890123456"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ActionF"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9b0c1d2-e3f4-5678-2345-678901234567"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ActionX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0c1d2e3-f4a5-6789-3456-789012345678"",
                    ""path"": ""<Keyboard>/equals"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Plus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1d2e3f4-a5b6-7890-4567-890123456789"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Plus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2e3f4a5-b6c7-8901-5678-901234567890"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Minus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3f4a5b6-c7d8-9012-6789-012345678901"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Minus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""f4a5b6c7-d8e9-0123-7890-123456789012"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a5b6c7d8-e9f0-1234-8901-234567890123"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b6c7d8e9-f0a1-2345-9012-345678901234"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c7d8e9f0-a1b2-3456-0123-456789012345"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d8e9f0a1-b2c3-4567-1234-567890123456"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Camera
            m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
            m_Camera_Pan = m_Camera.FindAction("Pan", throwIfNotFound: true);
            m_Camera_Scroll = m_Camera.FindAction("Scroll", throwIfNotFound: true);
            m_Camera_RotateButton = m_Camera.FindAction("RotateButton", throwIfNotFound: true);
            m_Camera_RotateDelta = m_Camera.FindAction("RotateDelta", throwIfNotFound: true);
            // Demo
            m_Demo = asset.FindActionMap("Demo", throwIfNotFound: true);
            m_Demo_Click = m_Demo.FindAction("Click", throwIfNotFound: true);
            m_Demo_MousePosition = m_Demo.FindAction("MousePosition", throwIfNotFound: true);
            m_Demo_Reset = m_Demo.FindAction("Reset", throwIfNotFound: true);
            m_Demo_Cancel = m_Demo.FindAction("Cancel", throwIfNotFound: true);
            m_Demo_Number1 = m_Demo.FindAction("Number1", throwIfNotFound: true);
            m_Demo_Number2 = m_Demo.FindAction("Number2", throwIfNotFound: true);
            m_Demo_Number3 = m_Demo.FindAction("Number3", throwIfNotFound: true);
            m_Demo_Number4 = m_Demo.FindAction("Number4", throwIfNotFound: true);
            m_Demo_Number5 = m_Demo.FindAction("Number5", throwIfNotFound: true);
            m_Demo_Number6 = m_Demo.FindAction("Number6", throwIfNotFound: true);
            m_Demo_Space = m_Demo.FindAction("Space", throwIfNotFound: true);
            m_Demo_ActionG = m_Demo.FindAction("ActionG", throwIfNotFound: true);
            m_Demo_ActionH = m_Demo.FindAction("ActionH", throwIfNotFound: true);
            m_Demo_ActionN = m_Demo.FindAction("ActionN", throwIfNotFound: true);
            m_Demo_ActionF = m_Demo.FindAction("ActionF", throwIfNotFound: true);
            m_Demo_ActionX = m_Demo.FindAction("ActionX", throwIfNotFound: true);
            m_Demo_Plus = m_Demo.FindAction("Plus", throwIfNotFound: true);
            m_Demo_Minus = m_Demo.FindAction("Minus", throwIfNotFound: true);
            m_Demo_Movement = m_Demo.FindAction("Movement", throwIfNotFound: true);
        }
        
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }
        
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }
        
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }
        
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;
        
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }
        
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }
        
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
        
        public void Enable()
        {
            asset.Enable();
        }
        
        public void Disable()
        {
            asset.Disable();
        }
        
        public IEnumerable<InputBinding> bindings => asset.bindings;
        
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }
        
        // Camera
        private readonly InputActionMap m_Camera;
        private readonly InputAction m_Camera_Pan;
        private readonly InputAction m_Camera_Scroll;
        private readonly InputAction m_Camera_RotateButton;
        private readonly InputAction m_Camera_RotateDelta;
        
        public struct CameraActions
        {
            private @SwarmDemoInputActions m_Wrapper;
            public CameraActions(@SwarmDemoInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Pan => m_Wrapper.m_Camera_Pan;
            public InputAction @Scroll => m_Wrapper.m_Camera_Scroll;
            public InputAction @RotateButton => m_Wrapper.m_Camera_RotateButton;
            public InputAction @RotateDelta => m_Wrapper.m_Camera_RotateDelta;
            public InputActionMap Get() { return m_Wrapper.m_Camera; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        }
        public CameraActions @Camera => new CameraActions(this);
        
        // Demo
        private readonly InputActionMap m_Demo;
        private readonly InputAction m_Demo_Click;
        private readonly InputAction m_Demo_MousePosition;
        private readonly InputAction m_Demo_Reset;
        private readonly InputAction m_Demo_Cancel;
        private readonly InputAction m_Demo_Number1;
        private readonly InputAction m_Demo_Number2;
        private readonly InputAction m_Demo_Number3;
        private readonly InputAction m_Demo_Number4;
        private readonly InputAction m_Demo_Number5;
        private readonly InputAction m_Demo_Number6;
        private readonly InputAction m_Demo_Space;
        private readonly InputAction m_Demo_ActionG;
        private readonly InputAction m_Demo_ActionH;
        private readonly InputAction m_Demo_ActionN;
        private readonly InputAction m_Demo_ActionF;
        private readonly InputAction m_Demo_ActionX;
        private readonly InputAction m_Demo_Plus;
        private readonly InputAction m_Demo_Minus;
        private readonly InputAction m_Demo_Movement;
        
        public struct DemoActions
        {
            private @SwarmDemoInputActions m_Wrapper;
            public DemoActions(@SwarmDemoInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Click => m_Wrapper.m_Demo_Click;
            public InputAction @MousePosition => m_Wrapper.m_Demo_MousePosition;
            public InputAction @Reset => m_Wrapper.m_Demo_Reset;
            public InputAction @Cancel => m_Wrapper.m_Demo_Cancel;
            public InputAction @Number1 => m_Wrapper.m_Demo_Number1;
            public InputAction @Number2 => m_Wrapper.m_Demo_Number2;
            public InputAction @Number3 => m_Wrapper.m_Demo_Number3;
            public InputAction @Number4 => m_Wrapper.m_Demo_Number4;
            public InputAction @Number5 => m_Wrapper.m_Demo_Number5;
            public InputAction @Number6 => m_Wrapper.m_Demo_Number6;
            public InputAction @Space => m_Wrapper.m_Demo_Space;
            public InputAction @ActionG => m_Wrapper.m_Demo_ActionG;
            public InputAction @ActionH => m_Wrapper.m_Demo_ActionH;
            public InputAction @ActionN => m_Wrapper.m_Demo_ActionN;
            public InputAction @ActionF => m_Wrapper.m_Demo_ActionF;
            public InputAction @ActionX => m_Wrapper.m_Demo_ActionX;
            public InputAction @Plus => m_Wrapper.m_Demo_Plus;
            public InputAction @Minus => m_Wrapper.m_Demo_Minus;
            public InputAction @Movement => m_Wrapper.m_Demo_Movement;
            public InputActionMap Get() { return m_Wrapper.m_Demo; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DemoActions set) { return set.Get(); }
        }
        public DemoActions @Demo => new DemoActions(this);
        
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1)
                    m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
    }
}
